import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Share } from "@capacitor/share";
import { Capacitor } from "@capacitor/core";
import { IonHeader, IonTitle, IonToolbar } from "@ionic/react";

export default function Home() {
  const share = async () => {
    await Share.share({
      title: "Simons YT Channel",
      text: "Learn to build awesome mobile apps!",
      url: "https://www.youtube.com/simongrimmdev_",
      dialogTitle: "Share with friends",
    });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {Capacitor.isNativePlatform() && (
        <IonHeader>
          <IonToolbar color="primary">
            <IonTitle>Capacitor App</IonTitle>
          </IonToolbar>
        </IonHeader>
      )}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          <h2>Cool channel</h2>
          <a onClick={() => share()}>Share now!</a>
        </p>
      </main>
    </div>
  );
}
